### ISSUE TITLE
Error in oneHot: depth must be >=2, but it is 1

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#20]
classification case. Output is attrition. Ignore all job, employee related features. All the rest as input.

Getting error message dealing with oneHot encoding when training the model : 'Error in oneHot: depth must be >=2, but it is 1' 
[1067_1925_bundle_archive.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4789330/1067_1925_bundle_archive.zip)

**Comment by hansvana** [comment]
Related: https://github.com/ml5js/ml5-library/issues/913

**Comment by hansvana** [comment]
The problem is with the feature "Over18", all values are "Y" so oneHot encoding gets a depth of 1. The only fix here is to provide a better error message for the user, so they know to disable features that only has one distinct value. Unfortunately I don't think there's any way for me to know which column is causing the problem, so that will be trial and error on the user's side.

**Comment by hansvana** [comment]
Alpha 0.2.3 provides a hopefully clearer error message for this case

**Comment by erikk-avans** [comment]
Checked. It works now.
